name: Make TWRP Device

on:
  push:
    tags:
      - "v.*" 

  workflow_dispatch:
    inputs:
      IMG_URL:    
        description: 'IMG_URL'
        required: true
        default: 'https://mirrorbits.lineageos.org/full/Mi439/20230419/recovery.img'

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - name: Check Out
      uses: actions/checkout@main
      
    - name: Prepare the environment
      run: |
        sudo apt update -y
        sudo apt -y install zip aria2 python-is-python3 python3 python3-pip cpio wget
        pip3 install twrpdtgen
        mkdir dt
      
    - name: Download boot or recovery img
      run: |
        aria2c "${{ github.event.inputs.IMG_URL }}"
        ls -lh
      
    - name: Start build
      run: |
        python3 -m twrpdtgen -o dt/ ./*.img && zip -r DeviceTree.zip ./dt

    - name: Create Release and Upload Release Asset
      uses: softprops/action-gh-release@v1
      with:
        tag_name: refs/tags/rectree
        name: refs/tags/Release
        body: TODO New Release.
        draft: false
        prerelease: false
        files: |
          DeviceTree.zip
