name: 编译 Dtreee TWRP

on:

  push:

    tags:

      - "v1.0"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout source

      uses: actions/checkout@v2

        

    - name: Install dependencies

      run: |

        sudo apt update -y

        sudo apt -y install zip aria2 python-is-python3 python3 python3-pip cpio wget

        pip3 install twrpdtgen

        mkdir dt

        

    - name: Download boot or recovery img

      run: |

        aria2c "https://mirrorbits.lineageos.org/full/Mi439/20230419/recovery.img"

        ls -lh

    - name: Build

      run: |

        python3 -m twrpdtgen -o dt/ ./*.img && zip -r DeviceTree.zip ./dt

      

    - name: Create Release

      id: create_release

      uses: actions/create-release@v1

      env:

        GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}

      with:

        tag_name: a

        release_name: Release sgg

        body: TODO New Release.

        draft: false

        prerelease: false

        

    - name: Upload Release Asset

      uses: actions/upload-release-asset@v1

      env:

        GITHUB_TOKEN: ${{ secrets.MY_TOKEN }}

      with:

        upload_url: ${{ steps.create_release.outputs.upload_url }}

        asset_path: DeviceTree.zip

        asset_name: DeviceTree.zip

        asset_content_type: application/zip
